# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.2.4
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: apex
  name: apex
spec:
  containers:
  - env:
    image: container-registry.oracle.com/database/free:latest
    name: db
    ports:
    - containerPort: 1521
      hostPort: 1521
    - containerPort: 8181
      hostPort: 8181
    - containerPort: 8443
      hostPort: 8443
    securityContext: {}
    volumeMounts:
    - mountPath: /opt/oracle/oradata
      name: oradata-pvc
  - args:
    - serve
    image: container-registry.oracle.com/database/ords:latest
    name: ords
    securityContext: {}
    depends_on:
    - db
    volumeMounts:
    - mountPath: /etc/ords/config
      name: ords_config-pvc
  volumes:
  - name: oradata-pvc
    persistentVolumeClaim:
      claimName: oradata
  - name: ords_config-pvc
    persistentVolumeClaim:
      claimName: ords_config
