set define '^' verify off
prompt ...patch_37473871.sql
--------------------------------------------------------------------------------
--
--  Copyright (c) 2025, Oracle and/or its affiliates.
--
--    NAME
--      patch_37473871.sql
--
--    DESCRIPTION
--      This script updates the templates report region on app 4000 page 622.
--
--    MODIFIED   (MM/DD/YYYY)
--    yadli      02/06/2025 - Created
--
--------------------------------------------------------------------------------
declare
    l_sql_clob clob;
begin
    l_sql_clob := wwv_flow_string.join(wwv_flow_t_varchar2(
                    'declare',
                    '  q varchar2(32767) := null;',
                    '  l_theme_refs wwv_flow_theme.t_refs;',
                    'begin',
                    '  l_theme_refs := wwv_flow_theme.get_refs_dev(',
                    '                              p_application_id => :P621_COPY_FROM_FLOW_ID );',
                    'q:=q||''select decode(ttype, '';',
                    'q:=q||''  ''''PAGE'''',wwv_flow_lang.system_message_lit(''''F4000.PAGE''''), '';',
                    'q:=q||''  ''''REGION'''',wwv_flow_lang.system_message_lit(''''F4000.REGION''''), '';',
                    'q:=q||''  ''''LABEL'''',wwv_flow_lang.system_message_lit(''''LABEL''''), '';',
                    'q:=q||''  ''''LIST'''',wwv_flow_lang.system_message_lit(''''F4000.LIST_INITCAP''''), '';',
                    'q:=q||''  ''''POPUP_LOV'''',wwv_flow_lang.system_message_lit(''''F4000.P371.POPUP_LOV''''), '';',
                    'q:=q||''  ''''CALENDAR'''',wwv_flow_lang.system_message_lit(''''LEGACY_CALENDAR''''), '';',
                    'q:=q||''  ''''MENU'''',wwv_flow_lang.system_message_lit(''''F4000.MENU''''), '';',
                    'q:=q||''  ''''BUTTON'''',wwv_flow_lang.system_message_lit(''''F4000.BUTTON''''), '';',
                    'q:=q||''  ''''REPORT'''',wwv_flow_lang.system_message_lit(''''REPORT''''), '';',
                    'q:=q||''  ''''POPUP_LOV'''',wwv_flow_lang.system_message_lit(''''F4000.P371.POPUP_LOV''''), '';',
                    'q:=q||''  ''''trans-''''||ttype) temp_type, '';',
                    'q:=q||''  tname from_template, '';',
                    '',
                    'q:=q||''  case when to_counter = 0 then '';',
                    'q:=q||''     ( select htmldb_item.hidden( 1, x.id ) '';',
                    'q:=q||''              || htmldb_item.hidden( 2, ta.temp_type )'';',
                    'q:=q||''              || htmldb_item.select_list_from_query_xl('';',
                    'q:=q||''                     3,'';',
                    'q:=q||'' 	                ta.theme_class_id || '''':'''' || ta.id,'';',
                    'q:=q||'' 	                ''''select wwv_flow_escape.html(name) d,'';',
                    'q:=q||''                              theme_class_id || '''''''':'''''''' || id v '';',
                    'q:=q||''                         from wwv_flow_templates_all '';',
                    'q:=q||''                        where ( flow_id, theme_id, security_group_id ) in '';',
                    'q:=q||''                              ( '';',
                    'q:=q||''                                ( '''' || :FB_FLOW_ID || '''', '';',
                    'q:=q||''                                  '''' || :FB_THEME_ID || '''', '';',
                    'q:=q||''                                  '''' || :WORKSPACE_ID || '''' ), '';',
                    'q:=q||''                                ( wwv_flow_theme_manager.get_central_application_id('';',
                    'q:=q||''                                      p_application_id => '''' || :FB_FLOW_ID || '''', '';',
                    'q:=q||''                                      p_theme_id       => '''' || :FB_THEME_ID  || '''' ), '';',
                    'q:=q||''                                  wwv_flow_theme_manager.get_central_theme_id('';',
                    'q:=q||''                                      p_application_id => '''' || :FB_FLOW_ID || '''', '';',
                    'q:=q||''                                      p_theme_id       => '''' || :FB_THEME_ID  || '''' ), '';',
                    'q:=q||''                                  wwv_flow_theme_manager.get_central_workspace_id('';',
                    'q:=q||''                                      p_application_id => '''' || :FB_FLOW_ID || '''', '';',
                    'q:=q||''                                      p_theme_id       => '''' || :FB_THEME_ID  || '''' ) )'';',
                    'q:=q||''                              )'''' || '';',
                    'q:=q||''                      ''''  and temp_type = '''''''''''' || x.ttype || '''''''''''' '';',
                    'q:=q||''                        order by 1'''', '';',
                    'q:=q||''                      ''''title= "'''' || '';',
                    'q:=q||''                               wwv_flow_lang.system_message( ''''F4000.P622.TO_TEMPLATE'''' ) || '';',
                    'q:=q||''                                                             ''''"'''',''''NO'''',null,null,null,null,''''NO''''	) '';',
                    'q:=q||''        from wwv_flow_templates_all ta '';',
                    'q:=q||''       where ( ta.flow_id, ta.theme_id, ta.security_group_id ) in '';',
                    'q:=q||''             ( '';',
                    'q:=q||''               ( :FB_FLOW_ID, '';',
                    'q:=q||''                 :FB_THEME_ID, '';',
                    'q:=q||''                 :WORKSPACE_ID ), '';',
                    'q:=q||''               ( wwv_flow_theme_manager.get_central_application_id('';',
                    'q:=q||''                     p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                     p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''                 wwv_flow_theme_manager.get_central_theme_id('';',
                    'q:=q||''                     p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                     p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''                 wwv_flow_theme_manager.get_central_workspace_id('';',
                    'q:=q||''                     p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                     p_theme_id       => :FB_THEME_ID ) )'';',
                    'q:=q||''             )'' ;',
                    'q:=q||'' 	      and ta.temp_type = x.ttype '';',
                    'q:=q||''         and rownum = 1 ) '';',
                    '',
                    'q:=q||''     when to_counter = 1 then '';',
                    'q:=q||''          ( select htmldb_item.hidden( 4, x.id )'';',
                    'q:=q||''                   || htmldb_item.hidden( 5, ta.temp_type )'';',
                    'q:=q||''                   || htmldb_item.hidden( 6, ta.theme_class_id || '''':'''' || ta.id )'';',
                    'q:=q||''                   || to_clob(wwv_flow_escape.html( ta.name ) collate using_nls_comp ) '';',
                    'q:=q||''              from wwv_flow_templates_all ta '';',
                    'q:=q||''             where ( ta.flow_id, ta.theme_id, ta.security_group_id ) in '';',
                    'q:=q||''                   ( '';',
                    'q:=q||''                     ( :FB_FLOW_ID, '';',
                    'q:=q||''                       :FB_THEME_ID, '';',
                    'q:=q||''                       :WORKSPACE_ID ), '';',
                    'q:=q||''                    ( wwv_flow_theme_manager.get_central_application_id('';',
                    'q:=q||''                          p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                          p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''                      wwv_flow_theme_manager.get_central_theme_id('';',
                    'q:=q||''                          p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                          p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''                      wwv_flow_theme_manager.get_central_workspace_id('';',
                    'q:=q||''                          p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                          p_theme_id       => :FB_THEME_ID ) )'';',
                    'q:=q||''                   )'' ;',
                    'q:=q||'' 	            and ta.theme_class_id = x.theme_class_id '';',
                    'q:=q||'' 	            and ta.temp_type = x.ttype '';',
                    'q:=q||''               and rownum = 1 ) '';',
                    '',
                    'q:=q||''     when to_counter > 1 then '';',
                    'q:=q||''         ( select htmldb_item.hidden( 1, x.id )'';',
                    'q:=q||''                  || htmldb_item.hidden( 2, ta.temp_type )'';',
                    'q:=q||''                  || htmldb_item.select_list_from_query_xl('';',
                    'q:=q||''                         3,'';',
                    'q:=q||''                         ( select theme_class_id || '''':'''' || id '';',
                    'q:=q||''                             from wwv_flow_templates_all '';',
                    'q:=q||''                            where ( flow_id, theme_id, security_group_id ) in '';',
                    'q:=q||''                                  ( '';',
                    'q:=q||''                                    ( :FB_FLOW_ID, '';',
                    'q:=q||''                                      :FB_THEME_ID, '';',
                    'q:=q||''                                      :WORKSPACE_ID ), '';',
                    'q:=q||''                                    ( wwv_flow_theme_manager.get_central_application_id('';',
                    'q:=q||''                                          p_application_id => :FB_FLOW_ID , '';',
                    'q:=q||''                                          p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''                                      wwv_flow_theme_manager.get_central_theme_id('';',
                    'q:=q||''                                          p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                                          p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''                                      wwv_flow_theme_manager.get_central_workspace_id('';',
                    'q:=q||''                                          p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                                          p_theme_id       => :FB_THEME_ID ) )'';',
                    'q:=q||''                                  )'' ;',
                    'q:=q||''                              and theme_class_id = x.theme_class_id '';',
                    'q:=q||''                              and name = x.tname '';',
                    'q:=q||''                              and rownum = 1 ), '';',
                    'q:=q||'' 	                    ''''select wwv_flow_escape.html( name ) d, '';',
                    'q:=q||''                                  theme_class_id || '''''''':'''''''' || id v '';',
                    'q:=q||''                             from wwv_flow_templates_all '';',
                    'q:=q||''                            where ( flow_id, theme_id, security_group_id ) in '';',
                    'q:=q||''                                  ( '';',
                    'q:=q||''                                    ( '''' || :FB_FLOW_ID || '''', '';',
                    'q:=q||''                                      '''' || :FB_THEME_ID || '''', '';',
                    'q:=q||''                                      '''' || :WORKSPACE_ID || '''' ), '';',
                    'q:=q||''                                    ( wwv_flow_theme_manager.get_central_application_id('';',
                    'q:=q||''                                          p_application_id => '''' || :FB_FLOW_ID || '''', '';',
                    'q:=q||''                                          p_theme_id       => '''' || :FB_THEME_ID  || '''' ), '';',
                    'q:=q||''                                      wwv_flow_theme_manager.get_central_theme_id('';',
                    'q:=q||''                                          p_application_id => '''' || :FB_FLOW_ID || '''', '';',
                    'q:=q||''                                          p_theme_id       => '''' || :FB_THEME_ID  || '''' ), '';',
                    'q:=q||''                                      wwv_flow_theme_manager.get_central_workspace_id('';',
                    'q:=q||''                                          p_application_id => '''' || :FB_FLOW_ID || '''', '';',
                    'q:=q||''                                          p_theme_id       => '''' || :FB_THEME_ID  || '''' ) )'';',
                    'q:=q||''                                  )'''' || '';',
                    'q:=q||''                           '''' and temp_type = '''''''''''' || x.ttype || '''''''''''' '';',
                    'q:=q||''                            order by 1 '''', '';',
                    'q:=q||''                          ''''title="'''' || wwv_flow_lang.system_message(''''F4000.P622.TO_TEMPLATE'''')'';',
                    'q:=q||''                                      || ''''"'''','';',
                    'q:=q||''                          ''''NO'''', null, null, null, null, ''''NO''''	) '';',
                    'q:=q||''              from wwv_flow_templates_all ta '';',
                    'q:=q||''             where ( ta.flow_id, ta.theme_id, ta.security_group_id ) in '';',
                    'q:=q||''                   ( '';',
                    'q:=q||''                     ( :FB_FLOW_ID, '';',
                    'q:=q||''                       :FB_THEME_ID, '';',
                    'q:=q||''                       :WORKSPACE_ID ), '';',
                    'q:=q||''                    ( wwv_flow_theme_manager.get_central_application_id('';',
                    'q:=q||''                          p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                          p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''                      wwv_flow_theme_manager.get_central_theme_id('';',
                    'q:=q||''                          p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                          p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''                      wwv_flow_theme_manager.get_central_workspace_id('';',
                    'q:=q||''                          p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                          p_theme_id       => :FB_THEME_ID ) )'';',
                    'q:=q||''                   )'' ;',
                    'q:=q||'' 	            and ( ( ta.theme_class_id = x.theme_class_id or ta.theme_class_id <> x.theme_class_id ) '';',
                    'q:=q||''                     or ta.theme_class_id = 0 or ta.theme_class_id is null ) '';',
                    'q:=q||'' 	            and ta.temp_type = x.ttype '';',
                    'q:=q||''               and rownum = 1 ) '';',
                    'q:=q||''end to_template, '';',
                    '',
                    'q:=q||'' case when to_counter > 1 then '';',
                    'q:=q||''          wwv_flow_lang.system_message_lit(''''WARNING_MULTIPLE_MATCHES'''') '';',
                    'q:=q||''      when to_counter = 1 then '';',
                    'q:=q||''          ''''<span class="a-Icon icon-check"></span>'''''';',
                    'q:=q||''      when to_counter = 0 then '';',
                    'q:=q||''          wwv_flow_lang.system_message_lit(''''WARNING_MISSING_CLASS'''') '';',
                    'q:=q||''end status '';',
                    '',
                    '',
                    '--end if;',
                    'q:=q||''from '';',
                    'q:=q||''(select '';',
                    'q:=q||''  p.flow_id, '';',
                    'q:=q||''  ''''PAGE'''' ttype, '';',
                    'q:=q||''  wwv_flow_escape.html(p.name) tname, '';',
                    'q:=q||''  p.theme_id, '';',
                    'q:=q||''  p.theme_class_id, '';',
                    'q:=q||''  p.id, '';',
                    'q:=q||''( select count(*) xx'';',
                    'q:=q||''    from wwv_flow_templates_all'';',
                    'q:=q||''   where ( flow_id, theme_id, security_group_id ) in '';',
                    'q:=q||''         ( '';',
                    'q:=q||''           ( :FB_FLOW_ID, '';',
                    'q:=q||''             :FB_THEME_ID, '';',
                    'q:=q||''             :WORKSPACE_ID ), '';',
                    'q:=q||''           ( wwv_flow_theme_manager.get_central_application_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_theme_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_workspace_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ) )'';',
                    'q:=q||''         )'' ;',
                    'q:=q||''     and theme_class_id = p.theme_class_id'';',
                    'q:=q||''     and is_popup = p.is_popup'';',
                    'q:=q||''     and temp_type = ''''PAGE'''') to_counter '';',
                    'q:=q||''from wwv_flow_templates p '';',
                    'q:=q||''where ( p.flow_id, p.theme_id, p.security_group_id ) in'';',
                    'q:=q||''      (('''''' || l_theme_refs(1).app_id || '''''', '''''' || l_theme_refs(1).theme_id || '''''', '''''' || l_theme_refs(1).sgid || ''''''),'';',
                    'q:=q||''       ('''''' || l_theme_refs(2).app_id || '''''', '''''' || l_theme_refs(2).theme_id || '''''', '''''' || l_theme_refs(2).sgid || ''''''))'';',
                    'q:=q||''      and id = nvl((select STEP_TEMPLATE from wwv_flow_steps where flow_id = :P621_COPY_FROM_FLOW_ID and id = :P621_COPY_FROM_PAGE_ID), '';',
                    'q:=q||''           (select t.default_page_template from wwv_flow_steps p, wwv_flows i, wwv_flow_themes t '';',
                    'q:=q||''             where p.flow_id  = :P621_COPY_FROM_FLOW_ID and p.id = :P621_COPY_FROM_PAGE_ID and i.id = p.flow_id '';',
                    'q:=q||''               and t.flow_id = i.id and t.theme_id = i.theme_id)) '';',
                    'q:=q||''union all '';',
                    'q:=q||''select distinct '';',
                    'q:=q||''p.flow_id, '';',
                    'q:=q||''''''REGION'''' ttype,  '';                                                                                                                    ',
                    'q:=q||''wwv_flow_escape.html(t.page_plug_template_name) tname, '';',
                    'q:=q||''t.theme_id, '';',
                    'q:=q||''t.theme_class_id, '';',
                    'q:=q||''t.id, '';',
                    'q:=q||''( select count(*) xx'';',
                    'q:=q||''    from wwv_flow_templates_all'';',
                    'q:=q||''   where ( flow_id, theme_id, security_group_id ) in '';',
                    'q:=q||''         ( '';',
                    'q:=q||''           ( :FB_FLOW_ID, '';',
                    'q:=q||''             :FB_THEME_ID, '';',
                    'q:=q||''             :WORKSPACE_ID ), '';',
                    'q:=q||''           ( wwv_flow_theme_manager.get_central_application_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_theme_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_workspace_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ) )'';',
                    'q:=q||''         )'' ;',
                    'q:=q||''     and theme_class_id = t.theme_class_id'';',
                    'q:=q||''     and temp_type = ''''REGION'''') to_counter '';',
                    'q:=q||''from wwv_flow_page_plugs p, '';',
                    'q:=q||''     wwv_flow_page_plug_templates t '';',
                    'q:=q||''where p.flow_id = :P621_COPY_FROM_FLOW_ID and '';',
                    'q:=q||''      p.page_id = :P621_COPY_FROM_PAGE_ID and '';',
                    'q:=q||''      p.plug_template = t.id (+) and '';',
                    'q:=q||''      t.page_plug_template_name is not null '';',
                    'q:=q||''union all '';',
                    'q:=q||''select      distinct i.flow_id, '';',
                    'q:=q||''''''LABEL'''' ttype, '';',
                    'q:=q||''wwv_flow_escape.html(f.TEMPLATE_NAME) tname, '';',
                    'q:=q||''f.theme_id, '';',
                    'q:=q||''f.theme_class_id, '';',
                    'q:=q||''f.id, '';',
                    'q:=q||''( select count(*) xx'';',
                    'q:=q||''    from wwv_flow_templates_all'';',
                    'q:=q||''   where ( flow_id, theme_id, security_group_id ) in '';',
                    'q:=q||''         ( '';',
                    'q:=q||''           ( :FB_FLOW_ID, '';',
                    'q:=q||''             :FB_THEME_ID, '';',
                    'q:=q||''             :WORKSPACE_ID ), '';',
                    'q:=q||''           ( wwv_flow_theme_manager.get_central_application_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_theme_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_workspace_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ) )'';',
                    'q:=q||''         )'' ;',
                    'q:=q||''     and theme_class_id = f.theme_class_id'';',
                    'q:=q||''     and temp_type = ''''LABEL'''') to_counter '';',
                    'q:=q||''from wwv_flow_field_templates f, '';',
                    'q:=q||''     wwv_flow_step_items i '';',
                    'q:=q||''where  '';',
                    'q:=q||''      i.flow_id = :P621_COPY_FROM_FLOW_ID and '';',
                    'q:=q||''     i.ITEM_FIELD_TEMPLATE = f.id(+) and '';',
                    'q:=q||''     i.flow_step_id = :P621_COPY_FROM_PAGE_ID and '';',
                    'q:=q||''     template_name is not null '';',
                    'q:=q||''union all '';',
                    'q:=q||''select a.flow_id, ''''POPUP_LOV'''' ttype, '';',
                    'q:=q||''wwv_flow_lang.system_message_lit(''''F4000.P371.POPUP_LOV'''') tname, '';',
                    'q:=q||''a.theme_id, '';',
                    'q:=q||''a.theme_class_id, '';',
                    'q:=q||''a.id, '';',
                    'q:=q||''( select count(*) xx'';',
                    'q:=q||''    from wwv_flow_templates_all'';',
                    'q:=q||''   where ( flow_id, theme_id, security_group_id ) in '';',
                    'q:=q||''         ( '';',
                    'q:=q||''           ( :FB_FLOW_ID, '';',
                    'q:=q||''             :FB_THEME_ID, '';',
                    'q:=q||''             :WORKSPACE_ID ), '';',
                    'q:=q||''           ( wwv_flow_theme_manager.get_central_application_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_theme_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_workspace_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ) )'';',
                    'q:=q||''         )'' ;',
                    'q:=q||''     and theme_class_id = a.theme_class_id'';',
                    'q:=q||''     and temp_type = ''''POPUP_LOV'''') to_counter '';',
                    'q:=q||''from wwv_flow_popup_lov_template a '';',
                    'q:=q||''where a.flow_id = :P621_COPY_FROM_FLOW_ID  '';',
                    'q:=q||''and a.theme_id = (select max(theme_id) from wwv_flows where id = :P621_COPY_FROM_FLOW_ID ) '';',
                    'q:=q||''and exists (select 1 '';',
                    'q:=q||''              from wwv_flow_step_items i '';',
                    'q:=q||''              where  '';',
                    'q:=q||''                    i.flow_id = :P621_COPY_FROM_FLOW_ID and '';',
                    'q:=q||''                    i.flow_step_id = :P621_COPY_FROM_PAGE_ID and '';',
                    'q:=q||''                    display_as like ''''POPUP%'''') '';',
                    'q:=q||''union all '';',
                    'q:=q||''select   distinct b.flow_id,''''BUTTON'''' ttype, '';',
                    'q:=q||''wwv_flow_escape.html(b.TEMPLATE_NAME) tname, '';',
                    'q:=q||''b.theme_id, '';',
                    'q:=q||''b.theme_class_id, '';',
                    'q:=q||''b.id, '';',
                    'q:=q||''( select count(*) xx'';',
                    'q:=q||''    from wwv_flow_templates_all'';',
                    'q:=q||''   where ( flow_id, theme_id, security_group_id ) in '';',
                    'q:=q||''         ( '';',
                    'q:=q||''           ( :FB_FLOW_ID, '';',
                    'q:=q||''             :FB_THEME_ID, '';',
                    'q:=q||''             :WORKSPACE_ID ), '';',
                    'q:=q||''           ( wwv_flow_theme_manager.get_central_application_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_theme_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_workspace_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ) )'';',
                    'q:=q||''         )'' ;',
                    'q:=q||''     and theme_class_id = b.theme_class_id'';',
                    'q:=q||''     and temp_type = ''''BUTTON'''') to_counter '';',
                    'q:=q||''from wwv_flow_button_templates b, '';',
                    'q:=q||''(select button_template_id, button_name '';',
                    'q:=q||'' from wwv_flow_step_buttons '';',
                    'q:=q||'' where flow_id = :P621_COPY_FROM_FLOW_ID and flow_step_id = :P621_COPY_FROM_PAGE_ID ) u '';',
                    'q:=q||''where b.flow_id = :P621_COPY_FROM_FLOW_ID and '';',
                    'q:=q||''      b.id = u.button_template_id ''; ',
                    'q:=q||''union all '';',
                    'q:=q||''select     distinct '';',
                    'q:=q||''t.flow_id, '';',
                    'q:=q||''''''CALENDAR'''' ttype, '';',
                    'q:=q||''wwv_flow_escape.html(t.name) tname, '';',
                    'q:=q||''t.theme_id, '';',
                    'q:=q||''t.theme_class_id, '';',
                    'q:=q||''t.id,  '';',
                    'q:=q||''( select count(*) xx'';',
                    'q:=q||''    from wwv_flow_templates_all'';',
                    'q:=q||''   where ( flow_id, theme_id, security_group_id ) in '';',
                    'q:=q||''         ( '';',
                    'q:=q||''           ( :FB_FLOW_ID, '';',
                    'q:=q||''             :FB_THEME_ID, '';',
                    'q:=q||''             :WORKSPACE_ID ), '';',
                    'q:=q||''           ( wwv_flow_theme_manager.get_central_application_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_theme_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_workspace_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ) )'';',
                    'q:=q||''         )'' ;',
                    'q:=q||''     and theme_class_id = t.theme_class_id'';',
                    'q:=q||''     and temp_type = ''''CALENDAR'''') to_counter '';',
                    'q:=q||''from  wwv_flow_cal_templates t, '';',
                    'q:=q||''      wwv_flow_cals c, '';',
                    'q:=q||''      wwv_flow_page_plugs r '';',
                    'q:=q||''where t.flow_id = :P621_COPY_FROM_FLOW_ID and '';',
                    'q:=q||''      c.flow_id = :P621_COPY_FROM_FLOW_ID and '';',
                    'q:=q||''      c.plug_id = r.id and '';',
                    'q:=q||''      r.page_id = :P621_COPY_FROM_PAGE_ID and '';',
                    'q:=q||''      r.flow_Id = :P621_COPY_FROM_FLOW_ID and '';',
                    'q:=q||''      t.id      = c.template_id '';',
                    'q:=q||''union all '';',
                    'q:=q||''select     distinct '';',
                    'q:=q||''t.flow_id, '';',
                    'q:=q||''''''MENU'''' ttype, '';',
                    'q:=q||''wwv_flow_escape.html(t.NAME) tname, '';',
                    'q:=q||''t.theme_id, '';',
                    'q:=q||''t.theme_class_id, '';',
                    'q:=q||''t.id, '';',
                    'q:=q||''( select count(*) xx'';',
                    'q:=q||''    from wwv_flow_templates_all'';',
                    'q:=q||''   where ( flow_id, theme_id, security_group_id ) in '';',
                    'q:=q||''         ( '';',
                    'q:=q||''           ( :FB_FLOW_ID, '';',
                    'q:=q||''             :FB_THEME_ID, '';',
                    'q:=q||''             :WORKSPACE_ID ), '';',
                    'q:=q||''           ( wwv_flow_theme_manager.get_central_application_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_theme_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_workspace_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ) )'';',
                    'q:=q||''         )'' ;',
                    'q:=q||''     and theme_class_id = t.theme_class_id'';',
                    'q:=q||''     and temp_type = ''''MENU'''') to_counter '';',
                    'q:=q||''from wwv_flow_menu_templates t, wwv_flow_page_plugs r '';',
                    'q:=q||''where t.flow_id = :P621_COPY_FROM_FLOW_ID and '';',
                    'q:=q||''      r.flow_id = :P621_COPY_FROM_FLOW_ID and '';',
                    'q:=q||''      r.page_id = :P621_COPY_FROM_PAGE_ID and '';',
                    'q:=q||''      r.menu_template_id = t.id '';',
                    'q:=q||''union all '';',
                    'q:=q||''select distinct '';',
                    'q:=q||''ro.flow_id, '';',
                    'q:=q||''''''REPORT'''' ttype, '';',
                    'q:=q||''wwv_flow_escape.html(ro.ROW_TEMPLATE_NAME) tname, '';',
                    'q:=q||''ro.theme_id, '';',
                    'q:=q||''ro.theme_class_id, '';',
                    'q:=q||''ro.id, '';',
                    'q:=q||''( select count(*) xx'';',
                    'q:=q||''    from wwv_flow_templates_all'';',
                    'q:=q||''   where ( flow_id, theme_id, security_group_id ) in '';',
                    'q:=q||''         ( '';',
                    'q:=q||''           ( :FB_FLOW_ID, '';',
                    'q:=q||''             :FB_THEME_ID, '';',
                    'q:=q||''             :WORKSPACE_ID ), '';',
                    'q:=q||''           ( wwv_flow_theme_manager.get_central_application_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_theme_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_workspace_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ) )'';',
                    'q:=q||''         )'' ;',
                    'q:=q||''     and theme_class_id = ro.theme_class_id'';',
                    'q:=q||''     and temp_type = ''''REPORT'''') to_counter '';',
                    'q:=q||''from wwv_flow_row_templates ro, '';',
                    'q:=q||''     wwv_flow_page_plugs r '';',
                    'q:=q||''where ro.flow_id = :P621_COPY_FROM_FLOW_ID and '';',
                    'q:=q||''      r.flow_id = :P621_COPY_FROM_FLOW_ID and '';',
                    'q:=q||''      r.page_id = :P621_COPY_FROM_PAGE_ID and '';',
                    'q:=q||''      r.PLUG_QUERY_ROW_TEMPLATE = ro.id '';',
                    'q:=q||''union all '';',
                    'q:=q||''select distinct t.flow_id, '';',
                    'q:=q||''       ''''LIST'''' ttype, '';',
                    'q:=q||''       wwv_flow_escape.html(t.list_template_name) tname, '';',
                    'q:=q||''       t.theme_id, '';',
                    'q:=q||''       t.theme_class_id, '';',
                    'q:=q||''       t.id, '';',
                    'q:=q||''( select count(*) xx'';',
                    'q:=q||''    from wwv_flow_templates_all'';',
                    'q:=q||''   where ( flow_id, theme_id, security_group_id ) in '';',
                    'q:=q||''         ( '';',
                    'q:=q||''           ( :FB_FLOW_ID, '';',
                    'q:=q||''             :FB_THEME_ID, '';',
                    'q:=q||''             :WORKSPACE_ID ), '';',
                    'q:=q||''           ( wwv_flow_theme_manager.get_central_application_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_theme_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ), '';',
                    'q:=q||''             wwv_flow_theme_manager.get_central_workspace_id('';',
                    'q:=q||''                 p_application_id => :FB_FLOW_ID, '';',
                    'q:=q||''                 p_theme_id       => :FB_THEME_ID ) )'';',
                    'q:=q||''         )'' ;',
                    'q:=q||''     and theme_class_id = t.theme_class_id'';',
                    'q:=q||''     and temp_type = ''''LIST'''') to_counter '';',
                    'q:=q||''from WWV_FLOW_LIST_TEMPLATES t, '';',
                    'q:=q||''     wwv_flow_page_plugs r '';',
                    'q:=q||''where t.flow_id = :P621_COPY_FROM_FLOW_ID and '';',
                    'q:=q||''      r.flow_id = :P621_COPY_FROM_FLOW_ID and '';',
                    'q:=q||''      r.page_id = :P621_COPY_FROM_PAGE_ID and '';',
                    'q:=q||''      r.list_template_id = t.id) x '';',
                    'q:=q||''order by 1 '';',
                    'return q;',
                    'end;'));

    update wwv_flow_page_plugs
       set plug_source = l_sql_clob
     where security_group_id = 10
       and flow_id between 4000 and 4009
       and page_id >= 622
       and page_id <  622 + 1
       and id      >= 200956404695128712
       and id      <  200956404695128712 + 1;
end;
/